In [18]:
#importing the Libraies

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [20]:
dataset

Age  Gender_male  Estimated_Salary  Actual  Predicted
0    27        False             96000       0          1
1    40         True             47000       0          0
2    28        False             87000       0          0
3    18        False             68000       0          0
4    44        False             39000       1          0
5    35         True             20000       0          0
6    36         True             99000       1          1
7    26         True             30000       0          0
8    27        False             58000       0          0
9    47        False             49000       1          1
10   35        False             57000       0          0
11   42        False             53000       0          0
12   42         True             73000       0          0
13   57        False            122000       1          1
14   41        False             51000       0          0
15   25         True             33000       0          0
16   48         True             33000       1          1
17   42         True             64000       0          0
18   36         True            144000       1          1
19   23        False             28000       0          0
20   43        False            112000       1          1
21   30         True             49000       0          0
22   35         True             50000       0          0
23   32         True             18000       0          0
24   37         True             77000       0          0
25   35         True             75000       0          0
26   26        False             15000       0          0
27   23         True             20000       0          0
28   45         True             22000       1          1
29   37         True             53000       0          0
30   21         True             88000       0          0
31   39         True             42000       0          0
32   53        False            104000       1          1
33   60         True             42000       1          1
34   26        False             35000       0          0
35   38        False            113000       1          1
36   39         True             77000       0          0
37   24        False             89000       0          0
38   42        False             80000       0          0
39   19         True             76000       0          0
40   34        False             25000       0          0
41   32        False            117000       1          1
42   29        False             83000       0          0
43   27         True             88000       0          0
44   35        False             25000       0          0

In [21]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [22]:
dataset

Age  Gender_male  Estimated_Salary  Actual  Predicted
0    27        False             96000       0          1
1    40         True             47000       0          0
2    28        False             87000       0          0
3    18        False             68000       0          0
4    44        False             39000       1          0
5    35         True             20000       0          0
6    36         True             99000       1          1
7    26         True             30000       0          0
8    27        False             58000       0          0
9    47        False             49000       1          1
10   35        False             57000       0          0
11   42        False             53000       0          0
12   42         True             73000       0          0
13   57        False            122000       1          1
14   41        False             51000       0          0
15   25         True             33000       0          0
16   48         True             33000       1          1
17   42         True             64000       0          0
18   36         True            144000       1          1
19   23        False             28000       0          0
20   43        False            112000       1          1
21   30         True             49000       0          0
22   35         True             50000       0          0
23   32         True             18000       0          0
24   37         True             77000       0          0
25   35         True             75000       0          0
26   26        False             15000       0          0
27   23         True             20000       0          0
28   45         True             22000       1          1
29   37         True             53000       0          0
30   21         True             88000       0          0
31   39         True             42000       0          0
32   53        False            104000       1          1
33   60         True             42000       1          1
34   26        False             35000       0          0
35   38        False            113000       1          1
36   39         True             77000       0          0
37   24        False             89000       0          0
38   42        False             80000       0          0
39   19         True             76000       0          0
40   34        False             25000       0          0
41   32        False            117000       1          1
42   29        False             83000       0          0
43   27         True             88000       0          0
44   35        False             25000       0          0

In [23]:
dataset=dataset.drop("Actual",axis=1)

In [24]:
dataset["Predicted"].value_counts()

Predicted
0    33
1    12
Name: count, dtype: int64

In [25]:
indep=dataset[["Age","Estimated_Salary","Gender_male"]]
dep=dataset["Predicted"]

In [26]:
indep.shape

(45, 3)

In [27]:
dep

0     1
1     0
2     0
3     0
4     0
5     0
6     1
7     0
8     0
9     1
10    0
11    0
12    0
13    1
14    0
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    1
29    0
30    0
31    0
32    1
33    1
34    0
35    1
36    0
37    0
38    0
39    0
40    0
41    1
42    0
43    0
44    0
Name: Predicted, dtype: int64

In [28]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [29]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.86      0.50      0.63        12
           1       0.25      0.67      0.36         3

    accuracy                           0.53        15
   macro avg       0.55      0.58      0.50        15
weighted avg       0.74      0.53      0.58        15

[[6 6]
 [1 2]]


In [30]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.80      1.00      0.89        12
           1       0.00      0.00      0.00         3

    accuracy                           0.80        15
   macro avg       0.40      0.50      0.44        15
weighted avg       0.64      0.80      0.71        15

[[12  0]
 [ 3  0]]


c:\Users\good4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\good4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\good4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

In [31]:
from sklearn.naive_bayes import CategoricalNB
classifier =CategoricalNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.80      1.00      0.89        12
           1       0.00      0.00      0.00         3

    accuracy                           0.80        15
   macro avg       0.40      0.50      0.44        15
weighted avg       0.64      0.80      0.71        15

[[12  0]
 [ 3  0]]


c:\Users\good4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\good4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\good4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

In [32]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [34]:

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.86      0.50      0.63        12
           1       0.25      0.67      0.36         3

    accuracy                           0.53        15
   macro avg       0.55      0.58      0.50        15
weighted avg       0.74      0.53      0.58        15

[[6 6]
 [1 2]]
