In [1]:
#importing the Libraies

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

Age  Gender_male  Estimated_Salary  Actual  Predicted
0    27        False             96000       0          1
1    40         True             47000       0          0
2    28        False             87000       0          0
3    18        False             68000       0          0
4    44        False             39000       1          0
5    35         True             20000       0          0
6    36         True             99000       1          1
7    26         True             30000       0          0
8    27        False             58000       0          0
9    47        False             49000       1          1
10   35        False             57000       0          0
11   42        False             53000       0          0
12   42         True             73000       0          0
13   57        False            122000       1          1
14   41        False             51000       0          0
15   25         True             33000       0          0
16   48         True             33000       1          1
17   42         True             64000       0          0
18   36         True            144000       1          1
19   23        False             28000       0          0
20   43        False            112000       1          1
21   30         True             49000       0          0
22   35         True             50000       0          0
23   32         True             18000       0          0
24   37         True             77000       0          0
25   35         True             75000       0          0
26   26        False             15000       0          0
27   23         True             20000       0          0
28   45         True             22000       1          1
29   37         True             53000       0          0
30   21         True             88000       0          0
31   39         True             42000       0          0
32   53        False            104000       1          1
33   60         True             42000       1          1
34   26        False             35000       0          0
35   38        False            113000       1          1
36   39         True             77000       0          0
37   24        False             89000       0          0
38   42        False             80000       0          0
39   19         True             76000       0          0
40   34        False             25000       0          0
41   32        False            117000       1          1
42   29        False             83000       0          0
43   27         True             88000       0          0
44   35        False             25000       0          0

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

Age  Gender_male  Estimated_Salary  Actual  Predicted
0    27        False             96000       0          1
1    40         True             47000       0          0
2    28        False             87000       0          0
3    18        False             68000       0          0
4    44        False             39000       1          0
5    35         True             20000       0          0
6    36         True             99000       1          1
7    26         True             30000       0          0
8    27        False             58000       0          0
9    47        False             49000       1          1
10   35        False             57000       0          0
11   42        False             53000       0          0
12   42         True             73000       0          0
13   57        False            122000       1          1
14   41        False             51000       0          0
15   25         True             33000       0          0
16   48         True             33000       1          1
17   42         True             64000       0          0
18   36         True            144000       1          1
19   23        False             28000       0          0
20   43        False            112000       1          1
21   30         True             49000       0          0
22   35         True             50000       0          0
23   32         True             18000       0          0
24   37         True             77000       0          0
25   35         True             75000       0          0
26   26        False             15000       0          0
27   23         True             20000       0          0
28   45         True             22000       1          1
29   37         True             53000       0          0
30   21         True             88000       0          0
31   39         True             42000       0          0
32   53        False            104000       1          1
33   60         True             42000       1          1
34   26        False             35000       0          0
35   38        False            113000       1          1
36   39         True             77000       0          0
37   24        False             89000       0          0
38   42        False             80000       0          0
39   19         True             76000       0          0
40   34        False             25000       0          0
41   32        False            117000       1          1
42   29        False             83000       0          0
43   27         True             88000       0          0
44   35        False             25000       0          0

In [6]:
dataset=dataset.drop("Actual",axis=1)

In [7]:
dataset

Age  Gender_male  Estimated_Salary  Predicted
0    27        False             96000          1
1    40         True             47000          0
2    28        False             87000          0
3    18        False             68000          0
4    44        False             39000          0
5    35         True             20000          0
6    36         True             99000          1
7    26         True             30000          0
8    27        False             58000          0
9    47        False             49000          1
10   35        False             57000          0
11   42        False             53000          0
12   42         True             73000          0
13   57        False            122000          1
14   41        False             51000          0
15   25         True             33000          0
16   48         True             33000          1
17   42         True             64000          0
18   36         True            144000          1
19   23        False             28000          0
20   43        False            112000          1
21   30         True             49000          0
22   35         True             50000          0
23   32         True             18000          0
24   37         True             77000          0
25   35         True             75000          0
26   26        False             15000          0
27   23         True             20000          0
28   45         True             22000          1
29   37         True             53000          0
30   21         True             88000          0
31   39         True             42000          0
32   53        False            104000          1
33   60         True             42000          1
34   26        False             35000          0
35   38        False            113000          1
36   39         True             77000          0
37   24        False             89000          0
38   42        False             80000          0
39   19         True             76000          0
40   34        False             25000          0
41   32        False            117000          1
42   29        False             83000          0
43   27         True             88000          0
44   35        False             25000          0

In [8]:
dataset["Predicted"].value_counts()


Predicted
0    33
1    12
Name: count, dtype: int64

In [9]:
indep=dataset[["Age", "Gender_male", "Estimated_Salary"]]
dep=dataset["Predicted"]

In [10]:
indep.shape

(45, 3)

In [11]:
dep

0     1
1     0
2     0
3     0
4     0
5     0
6     1
7     0
8     0
9     1
10    0
11    0
12    0
13    1
14    0
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    1
29    0
30    0
31    0
32    1
33    1
34    0
35    1
36    0
37    0
38    0
39    0
40    0
41    1
42    0
43    0
44    0
Name: Predicted, dtype: int64

In [12]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
        

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [14]:
y_pred = classifier.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [16]:
print(cm)

[[12  0]
 [ 1  2]]


In [17]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [18]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       1.00      0.67      0.80         3

    accuracy                           0.93        15
   macro avg       0.96      0.83      0.88        15
weighted avg       0.94      0.93      0.93        15



In [19]:
print(cm)

[[12  0]
 [ 1  2]]


In [20]:
age_input=float(input("Age:"))
salary_input=float(input("BMI:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

In [21]:
classifier.predict([[age_input,salary_input,sex_male_input]])

c:\Users\good4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [22]:
dir(clf_report)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri